version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: elkherchybaba
      POSTGRES_PASSWORD: kh@38405659
      POSTGRES_DB: sc3
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elkherchybaba -d sc3"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: /env/bin/python -m gunicorn --bind 0.0.0.0:8000 --workers 3 sc3.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy