# Generated by Django 5.1.6 on 2025-03-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('enseignant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('identifiant', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('groupe_id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('nom_groupe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('matiere_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_matiere', models.CharField(max_length=50)),
                ('nom_matiere', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('filiere', models.CharField(choices=[('TC', 'TC'), ('DWM', 'DWM'), ('DSI', 'DSI'), ('RSS', 'RSS')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MatiereEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
            options={
                'unique_together': {('enseignant', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='MatiereGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='TeacherGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe')),
            ],
            options={
                'unique_together': {('enseignant', 'groupe')},
            },
        ),
    ]
