# Generated by Django 5.1.6 on 2025-03-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargeHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_cm', models.IntegerField()),
                ('heures_td', models.IntegerField()),
                ('heures_tp', models.IntegerField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='DisponibilitesEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=9)),
                ('créneau_horaire', models.IntegerField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant')),
            ],
            options={
                'unique_together': {('enseignant', 'jour_semaine', 'créneau_horaire')},
            },
        ),
        migrations.CreateModel(
            name='ExceptionsPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exception', models.CharField(choices=[('ajout', 'ajout'), ('suppression', 'suppression')], max_length=15)),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=9)),
                ('créneau_horaire', models.IntegerField()),
                ('date', models.DateField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlanningHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=9)),
                ('créneau_horaire', models.IntegerField()),
                ('type_lecon', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=2)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere', 'enseignant', 'jour_semaine', 'créneau_horaire')},
            },
        ),
    ]
