# Generated by Django 5.1.6 on 2025-03-09 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('groupe_id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('nom_groupe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('matiere_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_matiere', models.CharField(max_length=50)),
                ('nom_matiere', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('filiere', models.CharField(choices=[('TC', 'Tronc Commun'), ('DWM', 'Développement Web et Mobile'), ('DSI', 'Data Science et Intelligence'), ('RSS', 'Réseaux et Systèmes de Sécurité')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=13)),
                ('creneau_horaire', models.IntegerField()),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enseignant', 'jour_semaine', 'creneau_horaire')},
            },
        ),
        migrations.CreateModel(
            name='GroupeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='ExceptionsPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exception', models.CharField(choices=[('ajout', 'Ajout'), ('suppression', 'Suppression')], max_length=13)),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=13)),
                ('creneau_horaire', models.IntegerField()),
                ('date', models.DateField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChargeHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_cm', models.IntegerField()),
                ('heures_td', models.IntegerField()),
                ('heures_tp', models.IntegerField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='MatiereTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('enseignant', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='PlanningHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=13)),
                ('creneau_horaire', models.IntegerField()),
                ('type_lecon', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2)),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere', 'enseignant', 'jour_semaine', 'creneau_horaire')},
            },
        ),
        migrations.CreateModel(
            name='TeacherGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
            ],
            options={
                'unique_together': {('enseignant', 'groupe')},
            },
        ),
    ]
